### ISSUE TITLE
check_distribution in brms

### ISSUE THREAD

**Issue by Chinca-lang** [easystats/performance#596] opened 2023-06-21 12:53 UTC
Dear all,

I think there is a little bug in the function check_distribution when using aterm in brm formula.
In this model:
>model <- brm(ALI|trials(10) ~Sex+ (1|ID),
                 chains = 10, iter = 5000, warmup = 1000,
                 refresh = 0,
                 data = data, family = binomial)

I obtain:
> check_distribution(model)
Error in `[.data.frame`(model_data, , rn, drop = FALSE) : 
  undefined columns selected

If I remove the trials it works perfectly.

Thanks for your work.
Best,

**Comment by strengejacke** [comment] 2023-06-21 13:06
Do you have a reproducible example?

**Comment by mattansb** [comment] 2023-06-21 13:23
This is a duplicate of https://github.com/easystats/insight/issues/779

**Comment by strengejacke** [comment] 2023-06-21 16:39
Not sure. I did not explicitly fix `trials()`, but I cannot reproduce that issue. Here's a working example:

``` r
library(brms)
## Probit regression using the binomial family
n <- sample(1:10, 100, TRUE)  # number of trials
success <- rbinom(100, size = n, prob = 0.4)
x <- rnorm(100)
data2 <- data.frame(n, success, x)
fit2 <- brm(success | trials(n) ~ x, data = data2,
            family = binomial("probit"))

head(insight::get_response(fit2))
#>   success  n
#> 1       3 10
#> 2       1  6
#> 3       1  4
#> 4       1  1
#> 5       2  6
#> 6       0  5
performance::check_distribution(fit2)
#> # Distribution of Model Family
#> 
#> Predicted Distribution of Residuals
#> 
#>  Distribution Probability
#>        normal         72%
#>        cauchy         28%
#> 
#> Predicted Distribution of Response
#> 
#>                Distribution Probability
#>  neg. binomial (zero-infl.)         47%
#>        poisson (zero-infl.)         28%
#>               beta-binomial         25%
```

<sup>Created on 2023-06-21 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by mattansb** [comment] 2023-06-21 17:19
This is a duplicate - when the `aterm` has a constant (not a data column), you get the error:

```R
library(brms)

fit4 <- brm(am | trials(1) ~ hp,
            data = mtcars, family = binomial(),
            backend = "cmdstanr", cores = 4)

insight::get_response(fit4) # source = "environment"
#> Error in `[.data.frame`(model_data, , rn, drop = FALSE) : 
#>   undefined columns selected

insight::get_response(fit4, source = "mf")
#> Error in `[.data.frame`(model_data, , rn, drop = FALSE) : 
#>   undefined columns selected
```

This also means that your fix at https://github.com/easystats/insight/pull/781 is wrong for this bug:

1. If the `aterm` uses a variable from the data, that should be returned (regardless of the `aterm` type).
2. If is it a constant, don't return it.

**Closed by mattansb** 2023-06-21 17:19 UTC
Labels: reprex :bar_chart:
