### ISSUE TITLE
Are there plans to support factor (coded) outcomes for logistic regression?

### ISSUE THREAD

**Issue by krassowski** [easystats/performance#449] opened 2022-07-14 13:49 UTC
Let's take the example from readme:

```R
model <- glm(am ~ wt + cyl, data = mtcars, family = binomial)
check_model(model)
```

This one works fine. Let's create a new column in mtcars which will code am as "automatic" or "manual" for ease of interpretation:

```R
mtcars$transmission_type = relevel(
    as.factor(ifelse(mtcars$am, 'automatic', 'manual')),
    ref='manual'
)
factor_model <- glm(transmission_type ~ wt + cyl, data = mtcars, family = binomial)
check_model(factor_model)
```

This results in:

```
Error in `$<-.data.frame`(`*tmp*`, "group", value = "yes"): replacement has 1 row, data has 0
Traceback:

1. check_model(model)
2. check_model.default(model)
3. suppressWarnings(.check_assumptions_glm(x, minfo))
4. withCallingHandlers(expr, warning = function(w) if (inherits(w, 
 .     classes)) tryInvokeRestart("muffleWarning"))
5. .check_assumptions_glm(x, minfo)
6. binned_residuals(model)
7. `$<-`(`*tmp*`, "group", value = "yes")
8. `$<-.data.frame`(`*tmp*`, "group", value = "yes")
9. stop(sprintf(ngettext(N, "replacement has %d row, data has %d", 
 .     "replacement has %d rows, data has %d"), N, nrows), domain = NA)
```

This can also be reproduced by running `binned_residuals(factor_model)`.

Similarly, `r2(factor_model)` does not work:

```
Warning message in .set_back_labels(as.numeric(as.character(x)), x):
“NAs introduced by coercion”
Warning message in min(x, na.rm = TRUE):
“no non-missing arguments to min; returning Inf”
$R2_Tjur = Tjur's R2: NaN
```

**Comment by bwiernik** [comment] 2022-07-14 14:34
Both of those work fine for me. Install the latest versions of the easystats packages and try again:

```r
install.packages("easystats", repos = "https://easystats.r-universe.dev")
easystats::install_latest()
```

**Comment by krassowski** [comment] 2022-07-14 14:42
Thank you for testing. Unfortunately, it still does not work for me. I have run the suggested command which upgraded the following packages:

| Package     |   Latest | Installed |
| --------------|--------|------------ |
| insight     | 0.18.0.1 |    0.18.0 |
| datawizard  |  0.4.1.8 |   0.4.1.7 |
| performance |  0.9.1.1 |     0.9.1 |
| modelbased  |  0.8.1.1 |     0.8.1 |
| correlation |  0.8.1.1 |     0.8.1 |
| see         |  0.7.1.1 |     0.7.1 |
| report      |  0.5.1.2 |   0.5.1.1 |

I restarted R and still see this problem. Here is my session info:

```
R version 4.1.2 (2021-11-01)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 22.04 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.10.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.10.0

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8    
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.1.2      tools_4.1.2         datawizard_0.4.1.8 
[4] performance_0.9.1.1 insight_0.18.0.1
```

Could there be any other dependencies which I shall try upgrading?

**Comment by krassowski** [comment] 2022-07-14 15:07
So 11 days ago there was a change in `datawizard::data_to_numeric` in this commit: https://github.com/easystats/datawizard/commit/06d6f9ee534ac58730891532e8c16963a4b1c66c CC @IndrajeetPatil.

The previous version was reducing to:

```R
response = insight::get_response(factor_model, verbose = FALSE)
(isTRUE(preserve_levels) && anyNA(suppressWarnings(as.numeric(as.character(stats::na.omit(x))))))
```

which returned TRUE.

The current version reduces to:

```R
response = insight::get_response(factor_model, verbose = FALSE)
(isTRUE(preserve_levels) && anyNA(suppressWarnings(to_numeric(stats::na.omit(x)))))
```

And this one returns FALSE. This is surprising, as the new `to_numeric` looks pretty similar to the old version:

```
to_numeric <- function(x) {
  tryCatch(as.numeric(as.character(x)),
    error = function(e) x,
    warning = function(w) x
  )
}
```

Yet, it works differently. Compare:

> ```R
> as.numeric(as.character(stats::na.omit(response)))
> ```

> Warning message in eval(expr, envir, enclos):
> “NAs introduced by coercion”
> <NA><NA><NA><NA><NA><NA><NA><NA><NA><NA><NA><NA><NA><NA><NA><NA><NA><NA><NA><NA><NA><NA><NA><NA><NA><NA><NA><NA><NA><NA><NA><NA>

with

> ```R
> to_numeric(stats::na.omit(response))
> ```

>  [1] automatic automatic automatic manual    manual    manual    manual   
> [8] manual    manual    manual    manual    manual    manual    manual   
> [15] manual    manual    manual    automatic automatic automatic manual   
> [22] manual    manual    manual    manual    automatic automatic automatic
> [29] automatic automatic automatic automatic
> Levels: manual automatic

**Comment by krassowski** [comment] 2022-07-14 15:16
Downgrading `datawizard` to 0.4.0 "fixed" this issue for me. Installing 0.4.1 from CRAN solves the issue as well. After installation the latest version with `easystats::install_latest()` I can reproduce the problem again. I am not sure how to install 0.4.1.6 to narrow down the range further (well, other than by installing manually from GitHub?).

I guess some remedial action still needs to be taken in `datawizard` package. Would you like me to open an issue over there, or do you prefer to avoid extra noise?

**Comment by krassowski** [comment] 2022-07-14 17:14
> Still not encountering any issue with _datawizard_ 0.4.1.8 installed from `easystats::install_latest()` just now.

@bwiernik:
- does `as.numeric(as.character(stats::na.omit(as.factor(ifelse(mtcars$am, 'automatic', 'manual')))))` result in a warning "NAs introduced by coercion" in your setup? I guess the warning may not be raised if your settings suppress some of the warnings?
- does `datawizard::to_numeric(stats::na.omit(as.factor(ifelse(mtcars$am, 'automatic', 'manual'))))` return NAs or original factor?

**Comment by IndrajeetPatil** [comment] 2022-07-15 06:31
I have reverted the change made in [easystats/datawizard@06d6f9e](https://github.com/easystats/datawizard/commit/06d6f9ee534ac58730891532e8c16963a4b1c66c).

@krassowski Can you please check if the issue is resolved with the latest GitHub version of _datawizard_? Sorry for the trouble.

**Comment by krassowski** [comment] 2022-07-15 10:21
Yes, the latest version works fine - thank you!

**Comment by strengejacke** [comment] 2022-07-16 20:51
I still think the current behaviour of `data_to_numeric()` makes sense, so we should simply stick to the working solution here, or we add some arguments to `data_to_numeric()` to change behaviour (like `convert_string_levels_to_numeric`, but of course a better name... 😬 )

**Comment by DominiqueMakowski** [comment] 2022-07-17 00:41
correlation() has `include_factors` (https://github.com/easystats/correlation/blob/main/R/correlation.R#L257) to include factors and under the hood convert them to numeric. I suppose something like `include_strings` or `include_characters` would be consistent?

**Comment by bwiernik** [comment] 2022-07-17 05:23
We should just treat all of those types the same as factors (since they are converted to factors by the model)

**Closed** 2022-08-02 09:21 UTC
Labels: bug :bug:
