### ISSUE TITLE
Error: `check_model()` not implemented for models of class `lm` yet

### ISSUE THREAD

**Issue by DavidSimonRothschild** [easystats/performance#629] opened 2023-09-28 20:44 UTC
If I want to use the check_model () function with this linear model:

model <- lm(nwspol~polintr+cptppola+lrscale+agea+eduyrs,data=CH_Subset)
check_model(model)

**I get the error: Error: `check_model()` not implemented for models of class `lm` yet.**

If I try it with the linear model from your documentation 

m <- lm(mpg ~ wt + cyl + gear + disp, data = mtcars)

check_model(m)

It works perfectly well.

I am using R 4.3.1 and performance 0.10.5.

**Comment by strengejacke** [comment] 2023-09-28 21:03
Do you have a reproducible example? Or some data that replicates the issue?

**Comment by DavidSimonRothschild** [comment] 2023-09-29 07:28
The error only appears when I first run this on the ESS 10 (European Social Survey Round 10).

library(haven)
library(tidyverse)
library(utils)
ESS10 <- read_dta("Downloads/ESS10-2/ESS10.dta")

CH_Subset <- ESS10 %>% 
  filter(cntry == "CH")
  
CH_Data <- CH_Subset %>%
  dplyr::select(polintr, cptppola, lrscale, gndr, agea, eduyrs, nwspol)


CH_Subset <- drop_na(CH_Data)


If I save the data as a csv instead and import it, the function works perfectly.

**Comment by DavidSimonRothschild** [comment] 2023-09-29 07:29
This is the data as csv, but then I can t reproduce the error.

[CH_Subset.csv](https://github.com/easystats/performance/files/12762026/CH_Subset.csv)

**Comment by strengejacke** [comment] 2023-09-29 08:50
Ok, I can reproduce it with the dta-file. I _think_ it's a _haven_-related issue, will look into it. Using `datawizard` to load the data works:

``` r
library(easystats)
#> # Attaching packages: easystats 0.6.0.13
#> ✔ bayestestR  0.13.1.2     ✔ correlation 0.8.4.9000
#> ✔ datawizard  0.9.0        ✔ effectsize  0.8.6     
#> ✔ insight     0.19.5.6     ✔ modelbased  0.8.6.4   
#> ✔ performance 0.10.5.4     ✔ parameters  0.21.2.3  
#> ✔ report      0.5.7.11     ✔ see         0.8.0.5
library(tidyverse)

ESS10 <- data_read("d:/Downloads/ESS10.zip", convert_factors = FALSE)
#> Reading data...
#> Following 3 variables are empty:
#>   gndr13, yrbrn13 and rshipa13
#>   
#> Use `remove_empty_columns()` to remove them from the data frame.

CH_Subset <- ESS10 %>%
  filter(cntry == "CH")

CH_Data <- CH_Subset %>%
  dplyr::select(polintr, cptppola, lrscale, gndr, agea, eduyrs, nwspol)

CH_Subset <- drop_na(CH_Data)

model <- lm(nwspol ~ polintr + cptppola + lrscale + agea + eduyrs, data = CH_Subset)
check_model(model)
```

![](https://i.imgur.com/cNEGrxZ.png)

or:

``` r
library(easystats)
#> # Attaching packages: easystats 0.6.0.13
#> ✔ bayestestR  0.13.1.2     ✔ correlation 0.8.4.9000
#> ✔ datawizard  0.9.0        ✔ effectsize  0.8.6     
#> ✔ insight     0.19.5.6     ✔ modelbased  0.8.6.4   
#> ✔ performance 0.10.5.4     ✔ parameters  0.21.2.3  
#> ✔ report      0.5.7.11     ✔ see         0.8.0.5

ESS10 <- data_read("d:/Downloads/ESS10.dta", convert_factors = FALSE)
#> Reading data...
#> Following 3 variables are empty:
#>   gndr13, yrbrn13 and rshipa13
#>   
#> Use `remove_empty_columns()` to remove them from the data frame.

CH_Subset <- ESS10 |> 
  data_filter(cntry == "CH") |>
  data_select(c("polintr", "cptppola", "lrscale", "gndr", "agea", "eduyrs", "nwspol")) |>
  tidyr::drop_na()

model <- lm(nwspol ~ polintr + cptppola + lrscale + agea + eduyrs, data = CH_Subset)
check_model(model)
```

![](https://i.imgur.com/3ol2S1p.png)

<sup>Created on 2023-09-29 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by strengejacke** [comment] 2023-09-29 08:56
Ok, found it. Residuals are of class `haven_labelled()`, which currently does not work for `bayestestR::estimate_density()`, which is used to create the normality-plot. Thus, for now I recommend using `datawizard::data_read()` instead of the _haven_ package, until this issue is fixed in _bayestestR_.

**Comment by bwiernik** [comment] 2023-09-29 09:22
Or just convert labeled variables to numeric or factor. Per the haven documentation, they should not be left as “labeled” for analyses.

**Comment by strengejacke** [comment] 2023-09-29 09:24
True, but I understand that this is often missed. To avoid confusion, we should also try to "fix" this from our side, if possible. That's the reason why I prefer `data_read()` to import data, because it returns "regular" R classes w/o dropping label attributes.

**Closed** 2023-09-29 11:30 UTC
