### ISSUE TITLE
check_outliers mahalanobis error

### ISSUE THREAD

**Issue by dpmoriarity** [easystats/performance#553] opened 2023-03-11 00:32 UTC
Whenever I attempt to specify mahalanobis as the method for the "check_outliers" function the error: Error in solve.default(cov, ...) : 
  Lapack routine dgesv: system is exactly singular: U[1,1] = 0: comes up. This has come up across different datasets and with default as well as specified thresholds. Are there any suggestions?

reproducible example:
```r
library(tidyverse)
library(lavaan)
easystats::easystats_update()
library(easystats)
library(summarytools)


sample_size=200

PopMod <- '
 # direct effect
  depression ~ 0*adiposity
 # mediator
  inflammation ~ 0.274*adiposity
  depression ~ 0.125*inflammation
  # indirect effect (0.274*0.125)
  ab := 0.274*0.125
  # total effect
  total := 0 + (0.274*0.125)
  
  #simulate covariates
  
  inflammation~.25*SexProxy
  depression~.40*SexProxy
  inflammation~.60*Meds
  
'

set.seed(369)
dataset <- as.data.frame(simulateData(PopMod, sample.nobs = sample_size))

model<-lm(scale(depression)~scale(inflammation), data = dataset) 

check_outliers(model, method = "mahalanobis", threshold = list(mahalanobis = stats::qchisq(p = 1 - 0.001, df = ncol(dataset))))
```

**Comment by rempsyc** [comment] 2023-03-26 14:44
I can reproduce. This is due to base `stats::mahalanobis` function:

``` r

# [...]

model<-lm(scale(depression)~scale(inflammation), data = dataset) 

check_outliers(model, method = "mahalanobis")
#> Error in solve.default(cov, ...): Lapack routine dgesv: system is exactly singular: U[1,1] = 0

x <- as.data.frame(insight::get_modelmatrix(model))
head(x)
#>   (Intercept) scale(inflammation)
#> 1           1          -0.2385747
#> 2           1           0.2406425
#> 3           1           0.7154182
#> 4           1           0.1011629
#> 5           1          -0.5156620
#> 6           1           1.3905895

stats::mahalanobis(x, center = colMeans(x), cov = stats::cov(x))
#> Error in solve.default(cov, ...): Lapack routine dgesv: system is exactly singular: U[1,1] = 0
```

However, can be fixed by removing the intercept for the data.

``` r
x <- x[2]
out <- stats::mahalanobis(x, center = colMeans(x), cov = stats::cov(x))
```

Same as #563. Thanks for reporting. A fix will be submitted soon.

<sup>Created on 2023-03-26 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Closed** 2023-03-27 05:52 UTC
Labels: bug :bug:
