### ISSUE TITLE
Performance: check_outliers() does not work with gmler()

### ISSUE THREAD

**Issue by HedyehAhmadi** [easystats/performance#312] opened 2021-06-18 16:30 UTC
Hi - I am using a glmer() model with Gamma distribution and identity link.  The command check_outliers() use to work with cook's distance up to last week but now it takes a long time and does not work. If the model is using nAGQ=0, then it works but otherwise it won't. Unfortunately, I can't share a reproducible example due to privacy policy of my data.

**Comment by bwiernik** [comment] 2021-06-18 19:33
Can you share an example using some other data or randomly generated data? I cannot reproduce any issue when I use a toy dataset:

``` r
library(lme4)
#> Loading required package: Matrix
gm1a <- glmer(mpg ~ wt + (1 | cyl),
              data = mtcars, family = Gamma(link = "identity"))
performance::check_outliers(gm1a)
#> Warning in hatvalues.merMod(model): the hat matrix may not make sense for GLMMs

#> Warning in hatvalues.merMod(model): the hat matrix may not make sense for GLMMs

#> Warning in hatvalues.merMod(model): the hat matrix may not make sense for GLMMs
#> OK: No outliers detected.
```

<sup>Created on 2021-06-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by HedyehAhmadi** [comment] 2021-06-18 19:58
Thank you for the reply - let me give you more information about my model
and data which might help.

One of my models look like this:
internal <-
  glmer(internal~1 + PM.continuus + high.educ.categorical +
prnt.empl.categorical  + neighb_phenx_continuous +
overall.income.categorical + time.categorical.1or2
        +(1|site/subjectid), family = Gamma(link = "identity"),
       glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 1e5)),
data=long_OzNo2)


   - Number of obs: 17030,
   - number of groups:
   - number of subjectid:abcd_site, 8981;
   - number of site, 21

Hope this helps.

**Comment by bwiernik** [comment] 2021-06-18 22:31
Given that it appears to be an optimization issue, rather than an object structural issue (where it would fail immediately), I don't know that we can debug it without an example of it failing. Can you generate some random data that produces the issue? 

Or, another option would be to generate a synthetic dataset using the synthpop package:
https://pubmed.ncbi.nlm.nih.gov/32159513/
https://www.youtube.com/watch?v=mZkLlT0Jz7M

**Comment by bwiernik** [comment] 2021-06-18 22:31
You might also consider fitting your model with glmmTMB instead of lme4, which may work better.

**Comment by HedyehAhmadi** [comment] 2021-06-18 22:34
Thank you for your response.

The code does not fail per se but it just runs forever without any errors.
This was not the case last week, the code would just run smoothly in less
than a min.

**Comment by bwiernik** [comment] 2021-06-18 22:59
Install this version of the package and see what happens: 

```
remotes::install_github("easystats/performance", ref = "e09e275e781dd6b15bc9a8a9d60f127b85ca9aa6")
```

**Comment by HedyehAhmadi** [comment] 2021-06-21 15:19
Thank you for the suggestion -  using glmmTMB is not an option at this point as I have many scripts with glmer().

I re-installed the recommended version of the package and I still have the same issue.

I hope you don't mind if I ask you an additional question here. I know check_outliers() with cook's distance uses stats::qf(0.5, ncol(x), nrow(x) - ncol(x)) as threshold, where x is the model matrix. I am assuming x is the fixed-effect model matrix and NOT the random-effect model matrix, is my assumption correct?

**Comment by bwiernik** [comment] 2021-06-21 16:07
Nothing has changed recently about the function other than what was changed after the version I sent to you, so I suspect this is an issue with your specific data (which would also explain why you weren't previously encountering any issue). Do you see the same performance issue when you compute cooks distance directly:

```r
cooks.distance(model)
```

Note also that the hat matrix/cook's distance may not be meaningful for GL(M)Ms. 

(You could use RStudio or another text editor's Find in Files function to replace all instances of `glmer(` with `glmmTMB(`. glmer syntax is valid in glmmTMB.)


> I hope you don't mind if I ask you an additional question here. I know check_outliers() with cook's distance uses stats::qf(0.5, ncol(x), nrow(x) - ncol(x)) as threshold, where x is the model matrix. I am assuming x is the fixed-effect model matrix and NOT the random-effect model matrix, is my assumption correct?

Yes, these diagnositic statistics are generally looking at the impact on fixed effects parameter estimates. See here for more discussion: https://pubmed.ncbi.nlm.nih.gov/15558803/

**Comment by HedyehAhmadi** [comment] 2021-06-21 16:23
Thank you for all the very informative replies.

I don't have the same performance issue with cooks.distance(model) command and that's why I am switching to this base command but I will use the median F-distribution threshold similar to the performance package.

Thank you for the note that the hat matrix/cook's distance may not be meaningful for GL(M)Ms. I am aware of this possible issue. I am suing a linear model with identity link and I think I am okay there.

**Comment by bwiernik** [comment] 2021-06-22 19:22
That is odd--all check_outliers() really is a wrapper around those other functions. Can you run `debug(check_outliers)` and then step through it line by line and say where the function hangs?

**Comment by strengejacke** [comment] 2021-07-14 08:44
_bump_

**Comment by IndrajeetPatil** [comment] 2021-07-14 09:10
@HedyehAhmadi Please re-open if you continue to experience this issue and can produce a reproducible example. 
Closing for now.

**Closed by IndrajeetPatil** 2021-07-14 09:10 UTC
Labels: reprex :bar_chart:, waiting for response :love_letter:

**Comment by HedyehAhmadi** [comment] 2021-07-16 04:20
Hi - thank you for the follow up. Sorry I'm on maternity leave. I'll get
back to this as soon as I can.

Best,

Hedyeh
