### ISSUE TITLE
check_normality has maximum row limitation? 

### ISSUE THREAD

**Issue by jasonmoy28** [easystats/performance#265] opened 2021-04-13 16:22 UTC
I fit a model using lme4. I used `check_normality`. However, when the row of the data exceeded 5000, it will always give me this error: 

```r
'check_normality()' does not support models of class 'lmerMod'.
Error in attr(p.val, "object_name") <- .safe_deparse(substitute(x)) : 
  attempt to set an attribute on NULL
```

I have checked using different datasets. It always produces the same error, exactly at 5001 rows. I know there are alternatives like `check_distribution`, or `check_model`. But, I really want to use this. Is that reproducible from your end? If so, is that a bug that you can fix?

**Comment by IndrajeetPatil** [comment] 2021-04-13 16:37
I can reproduce this behavior:

# 180 observations

``` r
library(performance)
library(lme4)
#> Loading required package: Matrix

m1 <- lmer(Reaction ~ Days + (Days | Subject), sleepstudy)
check_normality(m1)
#> Warning: Non-normality of residuals detected (p < .001).
```

# > 24,000 observations

```r
library(forcats)

m2 <- lmer(tvhours ~ age + (age | race), forcats::gss_cat)
#> Warning in checkConv(attr(opt, "derivs"), opt$par, ctrl = control$checkConv, :
#> Model failed to converge with max|grad| = 0.362881 (tol = 0.002, component 1)
#> Warning in checkConv(attr(opt, "derivs"), opt$par, ctrl = control$checkConv, : Model is nearly unidentifiable: very large eigenvalue
#>  - Rescale variables?
check_normality(m2)
#> 'check_normality()' does not support models of class 'lmerMod'.
#> Error in attr(p.val, "object_name") <- .safe_deparse(substitute(x)): attempt to set an attribute on NULL
```

<sup>Created on 2021-04-13 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by strengejacke** [comment] 2021-05-17 07:07
Should be fixed in https://github.com/easystats/performance/commit/f7b62e063c6177c0a7ad312f978313669db7b8e5

**Comment by strengejacke** [comment] 2021-05-17 07:08
due to limitations of shapiro.test, which is limited to sample size < 5000

**Closed by strengejacke** 2021-05-17 07:07 UTC
Labels: bug :bug:
