### ISSUE TITLE
Marginal vs. conditional R2 for Bayesian models

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/performance#3] opened 2019-02-17 03:45 UTC
It would be a great feature to have something for that. Options are:

- Expand `R2_nakagawa` to work with Bayesian models
- Adapt `R2 MLM` to work with Bayesian models
- Create a function based on `rstanarm::bayes_R2`

For the last option, [this thread](https://discourse.mc-stan.org/t/marginal-and-conditional-r2-for-stans-glmms/4557/5) could be relevant:

> bayes_R2(model, re.form = NULL) vs bayes_R2(model, re.form = NA) is fine, but it shouldn’t be used to “test” a null hypothesis that the group-specific intercept and coefficients are irrelevant.

**Comment by strengejacke** [comment] 2019-02-19 07:57
> Expand R2_nakagawa to work with Bayesian models

That one isn't quite easy. I've tried starting to implement this for brms models, but it's not working very good.

**Comment by DominiqueMakowski** [comment] 2019-02-19 07:59
I gave it a try with the fixed vs. total R2, and compared the values to the marginal & conditional R2s for the frequentist version... it seems to correspond quite nicely... 

(Although we could do a systematic comparison in a vignette, for different kinds of models, to see how all these R2 relate to each other)

**Comment by strengejacke** [comment] 2019-02-19 08:18
It's less a statistical, but more a technical issue of how to make this work with brms. We should dig into the Bayes-r2-functions a bit (which is also based on LOO, see https://github.com/strengejacke/sjstats/blob/986460c73c73a8d4114c2586ca6fe66fb0894fc5/R/r2.R#L369).  Or this here: https://github.com/jgabry/bayes_R2

**Comment by DominiqueMakowski** [comment] 2019-02-19 09:07
Yes, especially that the rstanarm::bayes_R2's flexibility (works on general linear models, mixed, non-mixed and so on) makes it quite powerful... It could become the unifying game changer of the field. Thus, it might be worth it for us digging into it (and creating a deps-free, brms-friendly version??)

**Comment by strengejacke** [comment] 2019-02-26 09:23
I think we should remove option 1 here... the computation of `r2_nakagawa()` is not stable and not easy to implement for brmsfit or stanreg objects.

**Comment by DominiqueMakowski** [comment] 2019-02-26 09:33
For now, having the R2 Bayes "total' vs. "fixed" is quite satisfying (it can serve the same purpose as Nakagawa's), if we manage to have it for brms

**Comment by strengejacke** [comment] 2019-02-26 09:40
Paul just posted an answer, the issue is fixed in the current GitHub of brms. I try to check this later, and if we are safe to use both `re.form` and `re.formula` in one call to `bayes_R2()`.

**Comment by DominiqueMakowski** [comment] 2019-02-26 09:46
sidenote: this could benefit from being advertised through a blogpost ☺️

**Closed** 2019-03-01 15:38 UTC
