### ISSUE TITLE
Add model_performance for BFBayesFactor

### ISSUE THREAD

**Issue by mattansb** [easystats/performance#150] opened 2020-10-21 12:19 UTC
*@IndrajeetPatil  https://github.com/easystats/performance/issues/143#issuecomment-713520928*

I just had a couple more requests:

1. ci specifies the credible interval width, but there are no CIs in the output. Is it possible to include them instead of or in addition to SE?
(similar to JASP output) (see image below)

2. Is it possible to include these details in the model_performance output [for linear models of `BFBayesFactor`], so that I can get this into a dataframe that I can then use elsewhere?

![image](https://user-images.githubusercontent.com/11330453/92740506-14e1e980-f37e-11ea-91ff-626aee9b9c47.png)

Paging @strengejacke

**Comment by IndrajeetPatil** [comment] 2020-10-21 16:25
@strengejacke  This is the crux of the issue:

``` r
library(performance)
library(BayesFactor)

mod <- anovaBF(formula = Sepal.Length ~ Species, data = iris)

r2(mod, ci = 0.95, average = TRUE)
#> # Bayesian R2 with Standard Error
#> 
#>   Conditional R2: 0.611 [0.032]

as.data.frame(r2(mod, ci = 0.95, average = TRUE))
#> Error in as.data.frame.default(r2(mod, ci = 0.95, average = TRUE)): cannot coerce class '"r2_bayes"' to a data.frame

performance::model_performance(mod)
#> Error in UseMethod("model_performance"): no applicable method for 'model_performance' applied to an object of class "c('BFBayesFactor', 'BFOrNULL')"
```

**Comment by strengejacke** [comment] 2020-10-21 18:17
I'm not sure I understand the request here. How does the title of this issue match with your example? There is no `as.data.frame()` for the r2-functions, and it's not needed right now (at least not for the easystats-packages/-functions). And what's wrong with the related `print()` method?

**Comment by IndrajeetPatil** [comment] 2020-10-21 18:22
For one, the confidence intervals are present as attributes but not printed.

For another, as a user, I am not sure how can I further use this output. 
It's useful when it's printed, but apart from that I have no recourse to modifying it further (e.g., saving it in a dataframe with other related details like Bayes Factor values).

**Comment by IndrajeetPatil** [comment] 2020-10-21 18:33
So maybe here we can add another method for `BFBayesFactor`?
https://github.com/easystats/performance/blob/e31ddfc6d0e83b6dee65afa2168bd849cca99c1f/R/model_performance.bayesian.R

Given that @mattansb has just implemented it?
https://github.com/easystats/performance/blob/4af84141150f5c66ec9964b60e9db9167808e016/R/r2_bayes.R#L185

**Comment by mattansb** [comment] 2020-10-22 06:12
@strengejacke  Right this is 2 issues really:

1. Change the printing and structure of the output from `r2_bayes()`.
2. Add a `model_performance.BFBayesfactor()` for linear models that gives RMSE (`sqrt(sig2)`) and R2 (`r2_bayes()`).

**Comment by strengejacke** [comment] 2020-10-22 06:24
So the actual issue is to have a `model_performance.BFBayesfactor()` function. But why 1)?

**Comment by mattansb** [comment] 2020-10-22 06:25
1 - because currently there is much information hidden away as attributes (e.g., CI) that is not easily accessible and is not printed.

**Comment by strengejacke** [comment] 2020-10-22 06:44
I think 1) is a duplicate of https://github.com/easystats/performance/issues/76.

**Comment by mattansb** [comment] 2020-10-22 08:22
Oh, yes - seems so.

**Comment by IndrajeetPatil** [comment] 2020-10-22 09:18
Please let's try to resolve this before the next update because I am going to need this for `tidyBF` package update.

**Comment by strengejacke** [comment] 2020-10-22 09:25
What performance metrics make sense here? r2, ... ?

**Comment by mattansb** [comment] 2020-10-22 10:08
Only R2 and RMSE:

``` r
library(BayesFactor)
#> Loading required package: coda
#> Loading required package: Matrix
#> ************
#> Welcome to BayesFactor 0.9.12-4.3. If you have questions, please contact Richard Morey (richarddmorey@gmail.com).
#> 
#> Type BFManual() to open the manual.
#> ************
library(performance)

mod <- generalTestBF(mpg ~ hp + wt + cyl, data = mtcars, progress = FALSE)

params <- insight::get_parameters(mod)
#> Multiple `BFBayesFactor` models detected - posteriors are extracted from the first numerator model.
#> See help("get_parameters", package = "insight").

sigma_<- bayestestR::point_estimate(sqrt(params$sig2), "median")
R2 <- suppressWarnings(r2(mod)) # we already got the multiple model warning before, no need for it again

list(
  sigma= sigma_[[1]],
  R2 = R2[[1]]
)
#> $sigma
#> [1] 3.973997
#> 
#> $R2
#> [1] 0.579253
```

<sup>Created on 2020-10-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by IndrajeetPatil** [comment] 2020-10-22 10:09
But not the CIs for R^2?

**Comment by mattansb** [comment] 2020-10-22 10:10
As @strengejacke that is a sepearte issue #76.

Let me get a basic working version of model_performance working here, we can work from there.

**Comment by mattansb** [comment] 2020-10-22 10:42
``` r
library(BayesFactor)
library(performance)

model <- generalTestBF(carb ~ am + mpg, mtcars)

model_performance(model)
#> Multiple `BFBayesFactor` models detected - posteriors are extracted from the first numerator model.
#> See help("get_parameters", package = "insight").
#> # Indices of model performance
#> 
#>   R2 | Sigma
#> ------------
#> 0.01 |  1.64
model_performance(model[2])
#> # Indices of model performance
#> 
#>   R2 | Sigma
#> ------------
#> 0.25 |  1.40
model_performance(model[3])
#> # Indices of model performance
#> 
#>   R2 | Sigma
#> ------------
#> 0.49 |  1.16

model_performance(model, average = TRUE)
#> # Indices of model performance
#> 
#>   R2 | Sigma
#> ------------
#> 0.49 |  1.16
```

<sup>Created on 2020-10-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment] 2020-10-22 12:03
> Only R2 and RMSE:

But sigma is not the same as RMSE, or not?

**Comment by mattansb** [comment] 2020-10-22 12:10
Right - I got confused, it is suppose to be sigma (:

**Closed** 2020-10-22 12:54 UTC
Labels: enhancement :boom:
