### ISSUE TITLE
Error using check_model with lmer: argument 1 is not a vector

### ISSUE THREAD

**Issue by affectdata** [easystats/performance#348] opened 2021-08-01 23:49 UTC
Hi all,

Thanks for all the amazing work on easystats. I ran into an error when calling `check_model` on my lmer model object. I'm running the latest version from github. Other kinds of diagnostic plots do succeed, such as `plot(check_normality(fit))`. Reproducible error code:

``` r
library(tidyverse)
library(lme4)
#> Loading required package: Matrix
#> 
#> Attaching package: 'Matrix'
#> The following objects are masked from 'package:tidyr':
#> 
#>     expand, pack, unpack
library(performance)
packageVersion("performance")
#> [1] '0.7.3.1'

load(url("https://github.com/affectdata/bug_reports/raw/main/affect1.RData"))
glimpse(df)
#> Rows: 960
#> Columns: 6
#> $ Subject    <fct> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,…
#> $ Affect     <fct> Mild, Mild, Mild, Mild, Mild, Mild, Mild, Mild, Intense, In…
#> $ Room       <fct> Normal, Normal, Normal, Normal, Strong, Strong, Strong, Str…
#> $ Sentence   <fct> S1, S1, S2, S2, S1, S1, S2, S2, S1, S1, S2, S2, S1, S1, S2,…
#> $ Repetition <fct> R1, R2, R1, R2, R1, R2, R1, R2, R1, R2, R1, R2, R1, R2, R1,…
#> $ DV         <dbl> 0.7781893, 0.7677461, 0.5046300, 0.5839591, 0.8088306, 0.80…
fit <- lmer(DV ~ Affect*Room + (1|Subject/Affect/Room), data = df)
check_model(fit)
#> Error in order(plot_data$Cooks_Distance, decreasing = TRUE): argument 1 is not a vector
```

<sup>Created on 2021-08-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by strengejacke** [comment] 2021-11-13 11:05
Possible duplicate of #352

**Closed by strengejacke** 2021-11-13 11:05 UTC
Labels: bug :bug:
