### ISSUE TITLE
unable to install packages as URL are failing (error 404)

### ISSUE THREAD

**Issue by verajosemanuel** [easystats/performance#345] opened 2021-07-30 08:27 UTC
tried to install performance package dev version but any URL is failing. Tried to access using browser too (see below).
Any other package from CRAN or Github is installed ok.

```
> install.packages("performance", repos = "https://easystats.r-universe.dev")
Installing package into ‘C:/Users/joe/dashboard/renv/library/R-4.0/x86_64-w64-mingw32’
(as ‘lib’ is unspecified)
also installing the dependencies ‘bayestestR’, ‘insight’, ‘datawizard’

trying URL 'https://easystats.r-universe.dev/src/contrib/bayestestR_0.10.5.zip'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://easystats.r-universe.dev/src/contrib/bayestestR_0.10.5.zip'
In addition: Warning message:
In download.file(url, destfile, method, mode = "wb", ...) :
  cannot open URL 'https://easystats.r-universe.dev/src/contrib/bayestestR_0.10.5.zip': HTTP status was '404 Not Found'
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘bayestestR’ failed
trying URL 'https://easystats.r-universe.dev/src/contrib/insight_0.14.2.1.zip'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://easystats.r-universe.dev/src/contrib/insight_0.14.2.1.zip'
In addition: Warning message:
In download.file(url, destfile, method, mode = "wb", ...) :
  cannot open URL 'https://easystats.r-universe.dev/src/contrib/insight_0.14.2.1.zip': HTTP status was '404 Not Found'
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘insight’ failed
trying URL 'https://easystats.r-universe.dev/src/contrib/datawizard_0.2.0.zip'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://easystats.r-universe.dev/src/contrib/datawizard_0.2.0.zip'
In addition: Warning message:
In download.file(url, destfile, method, mode = "wb", ...) :
  cannot open URL 'https://easystats.r-universe.dev/src/contrib/datawizard_0.2.0.zip': HTTP status was '404 Not Found'
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘datawizard’ failed
trying URL 'https://easystats.r-universe.dev/src/contrib/performance_0.7.3.1.zip'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://easystats.r-universe.dev/src/contrib/performance_0.7.3.1.zip'
In addition: Warning message:
In download.file(url, destfile, method, mode = "wb", ...) :
  cannot open URL 'https://easystats.r-universe.dev/src/contrib/performance_0.7.3.1.zip': HTTP status was '404 Not Found'
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘performance’ failed
```

![NOTFOUND](https://user-images.githubusercontent.com/15836677/127624817-9cf4f7d9-d419-46bc-a1af-16339a2e4a57.png)

**Comment by IndrajeetPatil** [comment] 2021-07-30 08:43
Strange.

I can't reproduce this. Here is a reprex:

``` r
install.packages("performance", repos = "https://easystats.r-universe.dev")
#> Installing package into '/Users/patil/Library/R/x86_64/4.1/library'
#> (as 'lib' is unspecified)
#> 
#> The downloaded binary packages are in
#>  /var/folders/_p/55p16nb13cs7yy707d8l_v1s_rmpr4/T//Rtmpram5xk/downloaded_packages
```

<sup>Created on 2021-07-30 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 4.1.0 (2021-05-18)
#>  os       macOS Mojave 10.14.6        
#>  system   x86_64, darwin17.0          
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_US.UTF-8                 
#>  ctype    en_US.UTF-8                 
#>  tz       Europe/Berlin               
#>  date     2021-07-30                  
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version    date       lib source                       
#>  backports     1.2.1      2020-12-09 [1] CRAN (R 4.1.0)               
#>  cli           3.0.1      2021-07-17 [1] CRAN (R 4.1.0)               
#>  crayon        1.4.1      2021-02-08 [1] CRAN (R 4.1.0)               
#>  digest        0.6.27     2020-10-24 [1] CRAN (R 4.1.0)               
#>  ellipsis      0.3.2      2021-04-29 [1] CRAN (R 4.1.0)               
#>  evaluate      0.14       2019-05-28 [1] CRAN (R 4.1.0)               
#>  fansi         0.5.0      2021-05-25 [1] CRAN (R 4.1.0)               
#>  fs            1.5.0      2020-07-31 [1] CRAN (R 4.1.0)               
#>  glue          1.4.2      2020-08-27 [1] CRAN (R 4.1.0)               
#>  highr         0.9        2021-04-16 [1] CRAN (R 4.1.0)               
#>  htmltools     0.5.1.1    2021-01-22 [1] CRAN (R 4.1.0)               
#>  knitr         1.33       2021-04-24 [1] CRAN (R 4.1.0)               
#>  lifecycle     1.0.0      2021-02-15 [1] CRAN (R 4.1.0)               
#>  magrittr      2.0.1      2020-11-17 [1] CRAN (R 4.1.0)               
#>  pillar        1.6.2      2021-07-29 [1] CRAN (R 4.1.0)               
#>  pkgconfig     2.0.3      2019-09-22 [1] CRAN (R 4.1.0)               
#>  purrr         0.3.4      2020-04-17 [1] CRAN (R 4.1.0)               
#>  reprex        2.0.0      2021-04-02 [1] CRAN (R 4.1.0)               
#>  rlang         0.4.11     2021-04-30 [1] CRAN (R 4.1.0)               
#>  rmarkdown     2.9        2021-06-15 [1] CRAN (R 4.1.0)               
#>  rstudioapi    0.13       2020-11-12 [1] CRAN (R 4.1.0)               
#>  sessioninfo   1.1.1      2018-11-05 [1] CRAN (R 4.1.0)               
#>  stringi       1.7.3      2021-07-16 [1] CRAN (R 4.1.0)               
#>  stringr       1.4.0      2019-02-10 [1] CRAN (R 4.1.0)               
#>  styler        1.5.1.9000 2021-07-22 [1] Github (r-lib/styler@a8ec068)
#>  tibble        3.1.3      2021-07-23 [1] CRAN (R 4.1.0)               
#>  utf8          1.2.2      2021-07-24 [1] CRAN (R 4.1.0)               
#>  vctrs         0.3.8      2021-04-29 [1] CRAN (R 4.1.0)               
#>  withr         2.4.2      2021-04-18 [1] CRAN (R 4.1.0)               
#>  xfun          0.24       2021-06-15 [1] CRAN (R 4.1.0)               
#>  yaml          2.2.1      2020-02-01 [1] CRAN (R 4.1.0)               
#> 
#> [1] /Users/patil/Library/R/x86_64/4.1/library
#> [2] /Library/Frameworks/R.framework/Versions/4.1/Resources/library
```

</details>

Maybe it was just a temporary issue? Can you please try again and see if it works?

**Comment by verajosemanuel** [comment] 2021-07-30 09:41
same error. I guess if working inside a {renv} environment is affecting it.

My session info:
```

sessioninfo::session_info()
- Session info ---------------------------------------------------------------------------
 setting  value                       
 version  R version 4.0.5 (2021-03-31)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  Spanish_Spain.1252          
 ctype    Spanish_Spain.1252          
 tz       Europe/Paris                
 date     2021-07-30                  

- Packages -------------------------------------------------------------------------------
 ! package     * version    date       lib source                            
 P assertthat    0.2.1      2019-03-21 [?] CRAN (R 4.0.3)                    
 P cellranger    1.1.0      2016-07-27 [?] CRAN (R 4.0.3)                    
 P cli           3.0.1      2021-07-17 [?] CRAN (R 4.0.5)                    
 P colorspace    2.0-2      2021-06-24 [?] CRAN (R 4.0.5)                    
 P crayon        1.4.1      2021-02-08 [?] CRAN (R 4.0.3)                    
 P curl          4.3.2      2021-06-23 [?] CRAN (R 4.0.5)                    
 P data.table    1.14.0     2021-02-21 [?] CRAN (R 4.0.5)                    
 P DBI           1.1.1      2021-01-15 [?] CRAN (R 4.0.3)                    
 P digest        0.6.27     2020-10-24 [?] CRAN (R 4.0.3)                    
 P dplyr         1.0.7      2021-06-18 [?] CRAN (R 4.0.5)                    
 P DT            0.18       2021-04-14 [?] CRAN (R 4.0.5)                    
 P ellipsis      0.3.2      2021-04-29 [?] CRAN (R 4.0.5)                    
 P evaluate      0.14       2019-05-28 [?] CRAN (R 4.0.3)                    
 P fansi         0.5.0      2021-05-25 [?] CRAN (R 4.0.5)                    
 P fastmap       1.1.0      2021-01-25 [?] CRAN (R 4.0.3)                    
 P forcats       0.5.1      2021-01-27 [?] CRAN (R 4.0.3)                    
 P foreign       0.8-81     2020-12-22 [?] CRAN (R 4.0.5)                    
 P generics      0.1.0      2020-10-31 [?] CRAN (R 4.0.3)                    
 P glue          1.4.2      2020-08-27 [?] CRAN (R 4.0.3)                    
 P haven         2.4.1      2021-04-23 [?] CRAN (R 4.0.5)                    
 P hms           1.1.0      2021-05-17 [?] CRAN (R 4.0.5)                    
   htmltools     0.5.1.9006 2021-07-22 [1] Github (rstudio/htmltools@bc226a3)
 P htmlwidgets   1.5.3      2020-12-10 [?] CRAN (R 4.0.5)                    
 P knitr         1.33       2021-04-24 [?] CRAN (R 4.0.5)                    
 P lifecycle     1.0.0      2021-02-15 [?] CRAN (R 4.0.4)                    
 P lubridate     1.7.10     2021-02-26 [?] CRAN (R 4.0.5)                    
 P magrittr      2.0.1      2020-11-17 [?] CRAN (R 4.0.3)                    
 P munsell       0.5.0      2018-06-12 [?] CRAN (R 4.0.3)                    
 P openxlsx      4.2.4      2021-06-16 [?] CRAN (R 4.0.5)                    
 P pillar        1.6.1      2021-05-16 [?] CRAN (R 4.0.5)                    
 P pkgconfig     2.0.3      2019-09-22 [?] CRAN (R 4.0.3)                    
 P purrr         0.3.4      2020-04-17 [?] CRAN (R 4.0.3)                    
 P R6            2.5.0      2020-10-28 [?] CRAN (R 4.0.3)                    
 P Rcpp          1.0.7      2021-07-07 [?] CRAN (R 4.0.5)                    
 P readxl        1.3.1      2019-03-13 [?] CRAN (R 4.0.3)                    
   renv          0.13.2     2021-03-30 [1] CRAN (R 4.0.5)                    
 P rio           0.5.27     2021-06-21 [?] CRAN (R 4.0.5)                    
 P rlang         0.4.11     2021-04-30 [?] CRAN (R 4.0.5)                    
 P rmarkdown     2.9        2021-06-15 [?] CRAN (R 4.0.5)                    
 P scales        1.1.1      2020-05-11 [?] CRAN (R 4.0.3)                    
 P sessioninfo   1.1.1      2018-11-05 [?] CRAN (R 4.0.3)                    
 P stringi       1.7.3      2021-07-16 [?] CRAN (R 4.0.5)                    
 P tibble        3.1.2      2021-05-16 [?] CRAN (R 4.0.5)                    
 P tidyselect    1.1.1      2021-04-30 [?] CRAN (R 4.0.5)                    
 P utf8          1.2.1      2021-03-12 [?] CRAN (R 4.0.5)                    
 P vctrs         0.3.8      2021-04-29 [?] CRAN (R 4.0.5)                    
 P withr         2.4.2      2021-04-18 [?] CRAN (R 4.0.5)                    
 P xfun          0.24       2021-06-15 [?] CRAN (R 4.0.5)                    
 P yaml          2.2.1      2020-02-01 [?] CRAN (R 4.0.3)                    
 P zip           2.2.0      2021-05-31 [?] CRAN (R 4.0.5)                    

[1] C:/Users/jose/dashboard/renv/library/R-4.0/x86_64-w64-mingw32
[2] C:/Users/joe/AppData/Local/Temp/RtmpSGR0qK/renv-system-library
```

**Comment by strengejacke** [comment] 2021-07-30 12:32
Can you try

```r
  install.packages(c("insight", "datawizard", "bayestestR", "performance",
                     "parameters", "effectsize", "correlation", "modelbased",
                     "see", "report"), repos = "https://easystats.r-universe.dev")
```

**Comment by strengejacke** [comment] 2021-07-30 12:33
This is just a guess, but I see that installing a package when dependencies are already installed, it used this URL:

```
https://easystats.r-universe.dev/bin/windows/contrib/4.1/performance_0.7.3.1.zip
```

while in your case, dependencies are required, which will be downloaded from:

```r
https://easystats.r-universe.dev/src/contrib/bayestestR_0.10.5.zip
```

Maybe that makes a difference?

**Comment by verajosemanuel** [comment] 2021-08-06 07:00
seems so. I was in a hurry so ended installing CRAN Versions. Sorry

**Comment by IndrajeetPatil** [comment] 2021-08-06 07:08
Sorry for the troubles you are facing. We are currently in the middle of releasing these newer versions of packages on CRAN, and then hopefully you shouldn't face these issues.

Closing this for now.

**Closed by IndrajeetPatil** 2021-08-06 07:08 UTC
